### ISSUE TITLE
Fix the default name of the pod

### ISSUE THREAD

**Issue by alex-bezek** [ngrok/ngrok-operator#179]
### What happened

The default pod name created by our helm chart is overly verbose and confusing. It should be shortned to be more clear and guessable. 

### What you think should happen instead

The current name is `ngrok-ingress-controller-kubernetes-ingress-controller-manager` for me because it combines the release name and the default name https://github.com/ngrok/kubernetes-ingress-controller/blob/main/helm/ingress-controller/templates/_helpers.tpl#L28

Instead of using the regular name and the chart release name, we should just use the override if provided. 

### How to reproduce

install the chart and get the pods

This is related to https://github.com/ngrok/kubernetes-ingress-controller/issues/87 since the name is important for your ability to install multiple instances

**Comment by Abdiramen** [comment]
```
|                  | fullnameOverride              | nameOverride                                 | nothing                                |
|------------------|-------------------------------|----------------------------------------------|----------------------------------------|
| fullnameOverride | fullnameOverride + "-manager" | fullnameOverride                             | fullnameOverride                       |
| nameOverride     | fullnameOverride + "-manager" | chart.name + "-" + nameOverride + "-manager" | chart.name + nameOverride + "-manager" |
| nothing          | fullnameOverride + "-manager" | chart.name + nameOverride + "-manager"       | chart.name + "-" + release.name        |
```
for example:
  - if `nameOverride` is set to "my-ingress" then `ngrok-ingress-controller-my-ingress-manager-58d8dcbbf5-vlxp9` is then name
  - if `fullnameOverride` is to "my-ingress" then `my-ingress-manager-5865d886d5-x582h` is the name
  - if nothing is set set then default name of `ngrok-ingress-controller-kubernetes-ingress-controller-manxzprm` is used

@nijikokun the current naming scheme is undesirable to customers. I think it would be advantages to just drop the `release.name` from the default name all together. What do you thing?

**Comment by nijikokun** [comment]
1. It seems like we are suggesting users to set `release.name` when installing other libraries use `--generate-name` maybe we could leverage that.
2. However we can get the name down to `ngrok-ingress-controller` without the additional `kubernetes-ingress-controller` is desired. Even if that means following other libraries suit where they set the chart name to the company name.

**Comment by alex-bezek** [comment]
With the recent rename to `ngrok-operator` this doesn't seem to be an issue anymore. Installing the helm chart without providing any name overrides gets you a well formed set of pod names

```
ngrok-operator-agent-845d5cfb48-kz5hj     0/1     Running     0          36s
ngrok-operator-manager-5f96c465d4-9vfwv   1/1     Running     0          36s
```
